# Generated by Django 2.0.7 on 2018-07-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_slowa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slowa',
        ),
    ]
