# Generated by Django 2.0.7 on 2018-07-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_slowa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='slowo',
            new_name='text',
        ),
    ]
