# Generated by Django 2.0.7 on 2018-07-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_auto_20180731_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slowa',
            new_name='Stats',
        ),
    ]
