# Generated by Django 2.0.7 on 2018-07-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_auto_20180731_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Slowa',
        ),
    ]
