# Generated by Django 2.0.7 on 2018-08-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_auto_20180731_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slowa',
            new_name='Stats',
        ),
    ]
